version: "3"
services:
  dmaw1:
    build: .
    ports:
     - "8080:80"
    volumes:
     - .:/var/www

  dmaw2:
    build: .
    ports:
      - "8081:80"
    volumes:
      - .:/var/www

  dmaw3:
    build: .
    ports:
      - "8082:80"
    volumes:
      - .:/var/www
