version: "3"
services:
  dmaw1:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
    environment:
      - DMAW_ID=1
      - DMAW_COUNT=3

  dmaw2:
    build: .
    ports:
      - "8081:80"
    volumes:
      - .:/var/www
    environment:
      - DMAW_ID=2
      - DMAW_COUNT=3

  dmaw3:
    build: .
    ports:
      - "8082:80"
    volumes:
      - .:/var/www
    environment:
      - DMAW_ID=3
      - DMAW_COUNT=3
