version: "2"
services:
  dmaw1:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
    environment:
      - DMAW_ID=1
      - DMAW_COUNT=5

  dmaw2:
    build: .
    volumes:
      - .:/var/www
    environment:
      - DMAW_ID=2
      - DMAW_COUNT=5

  dmaw3:
    build: .
    volumes:
      - .:/var/www
    environment:
      - DMAW_ID=3
      - DMAW_COUNT=5

  dmaw4:
    build: .
    volumes:
      - .:/var/www
    environment:
      - DMAW_ID=4
      - DMAW_COUNT=5

  dmaw5:
    build: .
    volumes:
      - .:/var/www
    environment:
      - DMAW_ID=5
      - DMAW_COUNT=5
