    <?php
        $this->headTitle('Compare test details');
    ?>
    <h3>Data object comparison</h3>

    <?php
        echo $this->partial('partial/object-compare.phtml', [
            'requestData'   => $requestData,
            'responseData'  => $responseData,
        ]);
    ?>

    <h3>Data conversion comparisons</h3>

    <?php
        echo $this->partial('partial/conversion-compare.phtml', [
            'comparisons' => $comparisons,
        ]);
    ?>

    <a class="btn btn-primary" href="/" role="button">Reset</a>